# Generated by Django 3.1.2 on 2020-11-02 11:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0052_pagelogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexgloryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('glory_intro', models.CharField(help_text='荣誉页', max_length=255, verbose_name='荣誉页')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='gloryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('glory_intro', models.CharField(help_text='荣誉介绍', max_length=255, verbose_name='荣誉介绍')),
                ('glory_created_at', models.DateField(auto_now_add=True)),
                ('glory_body', wagtail.core.fields.StreamField([('文章', wagtail.core.blocks.RichTextBlock()), ('图片', wagtail.images.blocks.ImageChooserBlock(icon='image'))], blank=True, help_text='内容', null=True, verbose_name='内容')),
                ('glory_image', models.ForeignKey(blank=True, help_text='首页图', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='首页图')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
