# Generated by Django 3.1.2 on 2020-11-02 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('glory', '0002_remove_glorypage_glory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='glorypage',
            name='glory_created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
