# Generated by Django 3.1.2 on 2020-11-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('blog_title', models.CharField(help_text='博客名称', max_length=400, verbose_name='博客名称')),
                ('blog_intro', models.CharField(help_text='博客概要', max_length=400, verbose_name='博客概要')),
            ],
            bases=('wagtailcore.page',),
        ),
    ]
